version: '3'

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./dolibarr_db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=dolibarr
      - MYSQL_USER=dolibarr
      - MYSQL_PASSWORD=dolibarr
      - MARIADB_ROOT_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_RANDOM_ROOT_PASSWORD=no
    ports:
      - "3306:3306"

  dolibarr:
    image: upshift/dolibarr:latest
    container_name: dolibarr
    restart: unless-stopped
    depends_on:
        - mariadb
    ports:
        - "8200:80"
    environment:
      - DOLI_ADMIN_LOGIN=admin
      - DOLI_ADMIN_PASSWORD=admin
      - DOLI_DB_HOST=mariadb
      - DOLI_DB_NAME=dolibarr
      - DOLI_DB_USER=dolibarr
      - DOLI_DB_PASSWORD=dolibarr
      - TZ=Europe/Brussels #you can change this to according it to your location
      - LANG=fr_FR
      - DOLI_HTTPS=yourlocalhost
    volumes:
      - ./doli_html:/var/www/html
      - ./doli_docs:/var/www/documents

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8300:80"
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=root
