services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-dolidb}
      MYSQL_USER: ${MYSQL_USER:-dolidbuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dolidbpass}
    volumes:
      - /home/dolibarr_mariadb:/var/lib/mysql
    container_name: dolibarr_mariadb_1
  web:
    image: dolibarr/dolibarr:latest
    environment:
      DOLI_INIT_DEMO: ${DOLI_INIT_DEMO:-0}
      DOLI_DB_HOST: ${DOLI_DB_HOST:-mariadb}
      DOLI_DB_NAME: ${DOLI_DB_NAME:-dolidb}
      DOLI_DB_USER: ${DOLI_DB_USER:-dolidbuser}
      DOLI_DB_PASSWORD: ${DOLI_DB_PASSWORD:-dolidbpass}
      DOLI_URL_ROOT: ${DOLI_URL_ROOT:-http://0.0.0.0}
      DOLI_ADMIN_LOGIN: ${DOLI_ADMIN_LOGIN:-admin}
      DOLI_ADMIN_PASSWORD: ${DOLI_ADMIN_PASSWORD:-admin}
      DOLI_CRON: ${DOLI_CRON:-0}
      DOLI_CRON_KEY: ${DOLI_CRON_KEY:-mycronsecurekey}
      DOLI_COMPANY_NAME: ${DOLI_COMPANY_NAME:-MyBigCompany}
      WWW_USER_ID: ${WWW_USER_ID:-1000}
      WWW_GROUP_ID: ${WWW_GROUP_ID:-1000}
    ports:
      - '8080:8080'
    links:
      - mariadb
    volumes:
      - ${APP_DATA_DIR}/home/dolibarr_documents:/var/www/documents
      - ${APP_DATA_DIR}/home/dolibarr_custom:/var/www/html/custom
    container_name: dolibarr_web_1
