services:
  app_proxy:
    environment:
      APP_HOST: dolibarr_server_1
      APP_PORT: 88

  server:
    image: dolibarr/dolibarr:latest
    container_name: dolibarr_server_1
    restart: on-failure
    depends_on:
      - mariadb
    environment:
      DOLI_INSTALL_AUTO: "0"
      DOLI_ADMIN_LOGIN: admin
      DOLI_ADMIN_PASSWORD: admin
      DOLI_DB_HOST: mariadb
      DOLI_DB_NAME: dolibarr
      DOLI_DB_USER: dolibarr
      DOLI_DB_PASSWORD: dolibarr
    volumes:
      - ${APP_DATA_DIR}data/documents:/var/www/documents
      - ${APP_DATA_DIR}data/custom:/var/www/html/custom

  mariadb:
    image: mariadb:latest
    container_name: dolibarr_mariadb_1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dolibarr
      MYSQL_USER: dolibarr
      MYSQL_PASSWORD: dolibarr
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ${APP_DATA_DIR}data/mariadb:/var/lib/mysql
