version: "3.7"

services:
  dolibarr:
    image: monogramm/docker-dolibarr
    restart: unless-stopped
    environment:
      DOLI_AUTO_CONFIGURE: ""
    volumes:
      - ${APP_DATA_DIR}/dolibarr:/var/www/html
      - ${APP_DATA_DIR}/apps:/var/www/html/custom
      - ${APP_DATA_DIR}/config:/var/www/html/conf
      - ${APP_DATA_DIR}/theme:/var/www/html/theme/YOUR_CUSTOM_THEME
    ports:
      - 88:88
