version: '3'

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dolibarr
      MYSQL_USER: dolibarr
      MYSQL_PASSWORD: dolibarr
      MARIADB_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: no

  dolibarr:
    image: upshift/dolibarr:latest
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      DOLI_ADMIN_LOGIN: admin
      DOLI_ADMIN_PASSWORD: admin
      DOLI_DB_HOST: mariadb
      DOLI_DB_NAME: dolibarr
      DOLI_DB_USER: dolibarr
      DOLI_DB_PASSWORD: dolibarr
      TZ: Europe/Brussels
      LANG: fr_FR
      DOLI_HTTPS: yourlocalhost
    volumes:
      - dolibarr_html:/var/www/html
      - dolibarr_docs:/var/www/documents

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root

volumes:
  mariadb_data:
  dolibarr_html:
  dolibarr_docs:
