version: '3.7'
services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped  
    environment:
      MYSQL_DATABASE: dolibarr
      MYSQL_USER: dolibarr
      MYSQL_PASSWORD: dolibarr
      MARIADB_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: 'no'
      PORT: 3306
    volumes:
      - ${APP_DATA_DIR}/data/dolibarr_mariadb:/var/lib/mysql
    server:
    image: dolibarr/dolibarr:latest
    restart: on-failure
      environment:
      DOLI_INSTALL_AUTO: "0"
      DOLI_ADMIN_LOGIN: admin
      DOLI_ADMIN_PASSWORD: admin
      DOLI_DB_HOST: mariadb
      DOLI_DB_NAME: dolibarr
      DOLI_DB_USER: dolibarr
      DOLI_DB_PASSWORD: dolibarr
    volumes:
      - ${APP_DATA_DIR}/data/dolibarr_documents:/var/www/documents
      - ${APP_DATA_DIR}/data/dolibarr_custom:/var/www/html/custom
    container_name: dolibarr_server_1

